### ISSUE TITLE
No instruction to compile

### ISSUE THREAD

**Issue by ElectroBoy404NotFound** [Kyota-exe/Tonix#1]

**Comment by Kyota-exe** [comment]
I'll add a README.md that will include instructions to run MiskOS on a virtual machine when I can at least print something to the screen :p

As of now everything is logged to a serial port, so even if there were instructions to compile you wouldn't see anything.

**Comment by ElectroBoy404NotFound** [comment]
Oh nice! Good luck on the OS!

**Comment by Kyota-exe** [comment]
Finally added instructions on how to build Tonix after 4 months. It can even run bash now, give it a try :)
Let me know if you run into any issues.

**Comment by ElectroBoy404NotFound** [comment]
OK, I will try it!
